apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: debug
  namespace: debug
spec:
  releaseName: debug
  chart:
    spec:
      chart: debug
      sourceRef:
        kind: GitRepository
        name: debug
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
