apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ppserver
spec:
  interval: 1m
  url: https://github.com/denist-huma/flux2-kustomize-helm-example
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
